### ISSUE TITLE
Scroll to bottom is fired when I scroll screen and the page not loaded completely

### ISSUE THREAD

**Issue by fabiorogeriosj** [electricjs/electric#62]
When the docs-nav or CodeMirror not binded and I start scroll, my page auto scroll to the bottom after page loaded completely, see gif:

![electric1](https://user-images.githubusercontent.com/1442874/27284410-016f60c2-54cf-11e7-981a-7f512130d7dc.gif)

**Comment by protoEvangelion** [comment]
@fabiorogeriosj  The bug lies somewhere in the `electricjs.com/js/bundles/pvMBy.s` bundle.

When I disable that asset in dev tools, the auto scroll bug goes away.

I'm on the hunt!

**Comment by protoEvangelion** [comment]
We are going to have to wait until metal is refactored to bundle with Webpack.  

I was looking to find out if the problem was with the way Electric is implementing the **Reading Progress** component or if it was a problem with the component itself.

However, when trying to isolate the component, the gulp build progress is currently broken.

**Comment by jonathantneal** [comment]
The issue was that Electric was instructing Metal.js to redraw the DOM every time. This happened between the time of first paint, and once Metal render took place. As a result, browser was recalculating the scroll position based on the wrong DOM.

The following commit resolves this issue, as well as improves rendering performance: https://github.com/electricjs/electric/commit/d4bc67d4e8faed6adcfed44c7c68ad5e9f964a1a

The original bug can be verified by:

1. Opening a local instance of /docs/intro/what-why-and-how/
2. In developer tools, disabling cache and reducing network speed to Fast 3G.
3. Reloading the page, and between first draw of the page and page load, scrolling any small amount, up or down, that does not end at the very top or bottom of the page.
4. Waiting for page load to finish, at which point the page would snap to the bottom.

Once that no longer happens, you know the bug is resolved.

**Comment by Robert-Frampton** [comment]
Thanks for the details @jonathantneal
