### ISSUE TITLE
Electric support base tag or handle sub-folder deployment?

### ISSUE THREAD

**Issue by leonardomerlin** [electricjs/electric#79]
I'm trying to deploy `dist` folder into `domain.com/doc/*`. How can I do that?

What I already tried (and doesn't work) :
- [x] use `<base href="/doc/">`
- [x] set `data-senna-base-path`
- [x] use some kind of "replaceAll" strategy, onto `href="*"` or `src="*"` - almost work, but it's ugly =/

There is a better way to achieve that?

Awesome project, btw.

**Comment by Robert-Frampton** [comment]
Hey @leonardomerlin 

The latest release of Electric added a `basePath` option that should resolve this.

https://electricjs.com/docs/configuration.html#options

Since setting that property will mess with local development, also take a look at the `envOptions`. It let's you set options that only get applied when a flag is passed to the cli.

Can you test and let me know if it works for your use case?

**Comment by leonardomerlin** [comment]
Awesome! I will try it soon. :+1:

Thanks.

**Comment by Robert-Frampton** [comment]
Closing this for now, feel free to reopen if it does not resolve the issue.
